### ISSUE TITLE
CDO

### ISSUE THREAD

**Issue by mauwot** [fmaussion/salem#134]

**Comment by mauwot** [comment]
wrf pp-files produced by CDO 1.7.2 can not be read with salem

**Comment by fmaussion** [comment]
Sorry for my late reply! Do you by chance know the difference between the two?

In any case, salem will recognize a WRF file if the attributes are there and keep their name, so maybe CDO changed some of them...

**Comment by xunwang633** [comment]
CDO 1.7.2 changes some dimension names which can not be recognized by salem:
Time -> XTIME (this dose not seem to be a problem)
bottom_top -> lev (RuntimeError('zdimension not recognized') when calling interpz function)
bottom_top_stag -> lev_2 (cannot recognize variables to unstagger)
soil_layers_stag -> lev_3

Because we use CDO 1.7.2 to discard the spin-up time and after that the original wrfout files were deleted. So I just did some 'quick and dirty' changes in salem to make it work with CDO 1.7.2. But the newer CDO version does not have this problem.

**Comment by fmaussion** [comment]
> bottom_top_stag -> lev_2 (cannot recognize variables to unstagger)
> soil_layers_stag -> lev_3

Yeah this is ugly and should be avoided

> bottom_top -> lev (RuntimeError('zdimension not recognized') when calling interpz function)

Salem's `interpz` function works fine and is flexible, but it's quite slow. I would use salem for data analysis, but if you are talking about interpolating to pressure levels or computing diag variables for HAR (or similar) production, I would recommend to look at  https://wrf-python.readthedocs.io as well

**Comment by xunwang633** [comment]
@fmaussion Thanks for your reply and the recommendation of wrf-python pacakge!
