### ISSUE TITLE
ValueError: Length of passed values is 1, index implies 3784.

### ISSUE THREAD

**Issue by preritaagarwal** [fmaussion/salem#180]
Hi, 

I am trying to  replicate the following  example from salem library doc and I am getting this error '**ValueError: Length of passed values is 1, index implies 3784.'**

```
da = xr.DataArray(np.arange(20).reshape(4, 5), dims=['lat', 'lon'],
                      coords={'lat':np.linspace(0, 30, 4),
                              'lon':np.linspace(-20, 20, 5)})
   

da.salem  # the accessor is an object

da.salem.quick_map();
```

I am using jupyter notebook and geopandas version 0.5.1.
Could you please let me know where the issue might be?

Thanks!

**Comment by thejasbabu** [comment]
Facing the same issue. Can someone help?

**Comment by jlandmann** [comment]
I just quickly ran the code snippet you provided and it seems to work for me with the following versions: numpy:1.19.1, xarray 0.16.1, salem 0.3.0, geopandas 0.8.1.
Maybe consider updating/changing to these versions and check if the error occurs again. Otherwise a full traceback might help to locate where the error originates exactly.
