### ISSUE TITLE
Rotate WRF Winds to Earth-Relative Coordinates?

### ISSUE THREAD

**Issue by camilomarquez** [fmaussion/salem#182]
Hello
I have questions:
  Is it necessary to rotate the winds to earth coordinates that I get from WRF? How to do it? Considering that I am working with the lambert projection and I use salem to display-work the netcdfs.

[This article talks about the rotation of the winds in wrf](https://www-k12.atmos.washington.edu/~ovens/wrfwinds.html). It tells us that I have to do it because I occupy the lambert projection and I must occupy the following equation:
   Uearth = U * cosalpha - V * sinalpha
   Vearth = V * cosalpha + U * sinalpha

to obtain u and v in earth coordinates.

but is it necessary to rotate the coordinates as well?

In the article they say yes.

>  Then, those earth-relative components are used along with the rotate_vector() function of matplotlib's basemap to get the new coordinates on the map's x/y grid.   Urot, Vrot = map.rotate_vector(Uearth,Vearth,lons,lats)

but I understand that the staggered dimensions of the wind (u, v) have disappeared with salem.

I am confused, any comment is helpful.

Thank you very much for all this work @fmaussion et al, I am downscaling to study a glacier in Chile and the salem library is a great tool that solves many problems.

PS: I know that with wrf-python you can get uvmet but it is more elegant and easier to read multiple files with salem and xarray

Camilo,

**Comment by fmaussion** [comment]
> Is it necessary to rotate the winds to earth coordinates that I get from WRF? How to do it? Considering that I am working with the lambert projection and I use salem to display-work the netcdfs.

The rotation is only necessary if you want to compare the winds to north-oriented sensors for example. When displayed with salem, the winds follow the map projection x and y coordinates are are correct. if you plot the WRF winds on a plate-carree projection you need to rotate them.

This functionality is out of scope for salem though, because of the overlap with wrf-python and because I'm mostly alone, salem can't really grow as much as needed. I decided to remove most of the wrf diagnostics from salem for that reason: https://github.com/fmaussion/salem/issues/140

**Comment by camilomarquez** [comment]
Ty
