### ISSUE TITLE
salem could not properly parse the provided coordinate reference system (crs)

### ISSUE THREAD

**Issue by plutologic** [fmaussion/salem#183]
Hi there, I ran into a problem when using salem to mask data: 

ValueError: salem could not properly parse the provided coordinate reference system (crs). This could be due to errors in your data, in PyProj, or with salem itself. If this occurs unexpectedly, report an issue to https://github.com/fmaussion/salem/issues. Full log: 
crs: None ; 
My data may not be wrong, I have used it in plot before.
I don't know how to fix it.
I use python on win7, my salem version is 0.3.0; geopandas 0.6.3, pyproj 1.9.6.

**Comment by fmaussion** [comment]
Thanks for the report. With the information you provide, I cannot help much either. Did you have a look at: https://salem.readthedocs.io/en/stable/faq.html#why-is-my-dataset-not-supported-dataset-grid-not-understood-error ? 

If your file has a relatively easy to parse CRS, you could suggest a PR to add it to salem. Otherwise you can parse it yourself and give it to salem yourself: https://salem.readthedocs.io/en/stable/xarray_acc.html#custom-projection
